spring:
  datasource:
    url: jdbc:h2:mem:cryptodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

security:
  jwt:
    secret: VEVTVF9TRUNSRVRfVEhBVF9JUl9UT19LRUVQX0lUX1NFQ1JFVA==
    expiration-seconds: 3600

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
